### ISSUE TITLE
Demo as Development Build?

### ISSUE THREAD

**Issue by zebulonj** [0wczar/airframe-react#3] opened 2019-08-20 20:55 UTC
If the demo, which is beautiful, were published as a development build and therefore explorable using the React dev-tools... that would be an excellent way to help users understand the available components and relationships between those components.

**Comment by unski11ed** [comment] 2019-09-02 11:47
You can launch a development build of the Demo by cloning this public repo. Publishing development to remote demo server would increase the required bandwidth (and loading times) a lot, which would affect the demo experience negatively.

Feel free to clone this repo and check it out on your local machine.

**Comment by zebulonj** [comment] 2019-09-11 00:28
Huh. Didn't realize the demo was in this same repo.

**Comment by buncismamen** [comment] 2019-12-27 11:13
@zebulonj could you close this issue if the issue is solved ?

**Closed** 2019-12-27 15:55 UTC
